### ISSUE TITLE
[ERROR] The FastA is not index - please index file first and run again.

### ISSUE THREAD

**Issue by snashraf** [charite/asdpex#10]
java -jar asdpex-cli/target/asdpex-cli-0.2.jar  align -d scripts/data/ -s seqan/regionalign2vcf -o alignresults -q asdpex.sqlite
[ERROR] The FastA is not index - please index file first and run again.

Even though I have indexed the files but still getting same error . 

These are files that I already have so I have indexed it already.

[nsyed@hpclogin1 asdpex]$ ls scripts/data/genome/GRCh38.*
scripts/data/genome/GRCh38.fa  scripts/data/genome/GRCh38.fa.gz  scripts/data/genome/GRCh38.fa.gz.fai  scripts/data/genome/GRCh38.fa.gz.gzi

Thanks
Najeeb

**Comment by snashraf** [comment]
I think their are some others errors as well while running at different stages. Can you please look into that as well. 
like if you see this command:

java -jar asdpex-cli/target/asdpex-cli-0.2.jar   align -d data/ -s seqan/regionalign2vcf -o alignresults -q asdpex.sqlite
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: data/genome/GRCh38.fa
So Files is not present at this location too. 

and then this one:

ava -jar asdpex-cli/target/asdpex-cli-0.2.jar create-db -s asdpex.sqlite -d data
[INFO] Create database
[INFO] Opened database successfully
Table created successfully
Table created successfully
Table created successfully
java.io.FileNotFoundException: data/alts_accessions_GRCh38.p2 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.charite.compbio.asdpex.util.IOUtil.getBufferedReaderFromFileName(IOUtil.java:76)
	at de.charite.compbio.asdpex.io.parser.AccessionInfoParser.parse(AccessionInfoParser.java:63)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.createAlternativeScaffoldTables(CreateDatabaseCommand.java:100)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.run(CreateDatabaseCommand.java:72)
	at de.charite.compbio.asdpex.App.main(App.java:58)
[INFO] Updated alt scaffold accessions
java.io.FileNotFoundException: data/chr_accessions_GRCh38.p2 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.charite.compbio.asdpex.util.IOUtil.getBufferedReaderFromFileName(IOUtil.java:76)
	at de.charite.compbio.asdpex.io.parser.AccessionInfoParser.parse(AccessionInfoParser.java:63)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.createAlternativeScaffoldTables(CreateDatabaseCommand.java:103)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.run(CreateDatabaseCommand.java:72)
	at de.charite.compbio.asdpex.App.main(App.java:58)
[INFO] Updated chromosome accessions
[INFO] Updated regions
java.io.FileNotFoundException: data/genomic_regions_definitions.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.charite.compbio.asdpex.util.IOUtil.getBufferedReaderFromFileName(IOUtil.java:76)
	at de.charite.compbio.asdpex.io.parser.RegionInfoParser.parse(RegionInfoParser.java:58)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.createAlternativeScaffoldTables(CreateDatabaseCommand.java:112)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.run(CreateDatabaseCommand.java:72)
	at de.charite.compbio.asdpex.App.main(App.java:58)
java.io.FileNotFoundException: data/all_alt_scaffold_placement.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at de.charite.compbio.asdpex.util.IOUtil.getBufferedReaderFromFileName(IOUtil.java:76)
	at de.charite.compbio.asdpex.io.parser.AltScaffoldPlacementParser.parse(AltScaffoldPlacementParser.java:60)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.createAlternativeScaffoldTables(CreateDatabaseCommand.java:119)
	at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.run(CreateDatabaseCommand.java:72)
	at de.charite.compbio.asdpex.App.main(App.java:58)

**Comment by pnrobinson** [comment]
I am not sure whether this will work: GRCh38.fa.gz.fai 
Could you try uncompressing the GRCh38 file and then using samtools faidx on it?
Since the errors you are reporting are FileNotFound errors can you tell us if thedownload scripts have worked correctly? The scripts are set up so that the exact paths need to be used as well.

**Comment by snashraf** [comment]
Yes I unzipped it and zipped again and was getting same error again.

**Comment by pnrobinson** [comment]
You should have a directory & file structure that looks like this:
$ ls data/
alignments/                      all_alt_scaffold_placement.txt   alts_accessions_GRCh38.p2        chr_accessions_GRCh38.p2         genome/                          genomic_regions_definitions.txt  
$ ls data/genome/
GRCh38.fa  GRCh38.fa.fai  GRCh38.fa.gz

Can you show what you have?

**Comment by snashraf** [comment]
No when you download from script, you have only two files, GRCh38.fa  GRCh38.fa.gz. then it was complaining for indexing, then I unzipped the file and then zipped again with bgzip and then index it using faidx. and when I am running the complaining about .fa files.

**Comment by snashraf** [comment]
These are files 
[nsyed@hpclogin1 asdpex]$ ls /gpfs/projects/bioinfo/najeeb/tools/asdpex/scripts/data/genome/
GRCh38.fa  GRCh38.fa.gz  GRCh38.fa.gz.fai  GRCh38.fa.gz.gzi

**Comment by snashraf** [comment]
And when I removed this files from GRCh38.fa then I am getting this error.
java -jar asdpex-cli/target/asdpex-cli-0.2.jar  align -d /gpfs/projects/bioinfo/najeeb/tools/asdpex/scripts/data -s seqan/regionalign2vcf -o alignresults -q asdpex.sqlite
Exception in thread "main" htsjdk.samtools.SAMException: Error opening file: /gpfs/projects/bioinfo/najeeb/tools/asdpex/scripts/data/genome/GRCh38.fa
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:523)
	at htsjdk.samtools.reference.FastaSequenceFile.<init>(FastaSequenceFile.java:59)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:129)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:82)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:70)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getReferenceSequenceFile(ReferenceSequenceFileFactory.java:59)
	at de.charite.compbio.asdpex.cmd.AlignCommand.run(AlignCommand.java:82)
	at de.charite.compbio.asdpex.App.main(App.java:58)
Caused by: java.nio.file.NoSuchFileException: /gpfs/projects/bioinfo/najeeb/tools/asdpex/scripts/data/genome/GRCh38.fa
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at htsjdk.samtools.util.IOUtil.openFileForReading(IOUtil.java:519)
	... 7 more

**Comment by pnrobinson** [comment]
Something went wrong here
GRCh38.fa GRCh38.fa.gz GRCh38.fa.gz.fai GRCh38.fa.gz.gzi
You need to have the file
GRCh38.fa.fai  (not GRCh38.fa.gz.fai).
It looks as if you may have tried to index the gzip file
try 
$samtools faidx GRCh38.fa

**Comment by snashraf** [comment]
Thanks !! yes It happened because I indexed a bgzip files .
