### ISSUE TITLE
Error: Features added out of order

### ISSUE THREAD

**Issue by changd15** [charite/asdpex#11]
Hi, 
When I run asdpex-cli-0.2.jar, I get the following error on a few samples. I have ensured that the input files have been sorted. Any help would be greatly appreciated! Thanks!

**************[WARN] found no 'first' ASDP for region REGION160 set to region start.
[WARN] found no 'last' ASDP for region REGION160 set to region stop.
****Exception in thread "main" java.lang.IllegalArgumentException: Features added out of order: previous (TabixFeature{referenceIndex=13, start=105573251, end=105573293, featureStartFilePosition=451911835841, featureEndFilePosition=-1}) > next (TabixFeature{referenceIndex=13, start=105573221, end=105573267, featureStartFilePosition=451911836245, featureEndFilePosition=-1})
	at htsjdk.tribble.index.tabix.TabixIndexCreator.addFeature(TabixIndexCreator.java:89)
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.add(IndexingVariantContextWriter.java:170)
	at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:219)
	at de.charite.compbio.asdpex.cmd.AnnotatedVariantWriter.put(AnnotatedVariantWriter.java:62)
	at de.charite.compbio.asdpex.cmd.AnnotateVCFCommand.writeVariants(AnnotateVCFCommand.java:320)
	at de.charite.compbio.asdpex.cmd.AnnotateVCFCommand.run(AnnotateVCFCommand.java:292)
	at de.charite.compbio.asdpex.App.main(App.java:58)
make: *** [sortvcf] Error 1

**Comment by pnrobinson** [comment]
Can you provide a little more context? Can you provide the command-line arguments you used that led to this error?


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by changd15** [comment]
Sure thing. I have vcfs for several samples and am trying to run the ASDP extraction algorithm on them. The ASDP extraction ran successfully for a majority of the samples, but failed with above error for a few of them. I ran the following command:
	java -jar target/asdpex-cli-0.2.jar annotate -a allASDPs.SNV.50_10.valid.sorted.vcf.gz -d ${asdpdir}/data/ -v vcfs/${sample}_sorted.vcf.gz -o asdpex/${sample}_sorted.asdp.vcf.gz -s ${asdpdir}/asdpex.sqlite
