### ISSUE TITLE
missing genomic_regions_definitions.txt

### ISSUE THREAD

**Issue by GodloveD** [charite/asdpex#13]
I'm an admin with no omics background attempting to install this package on behalf of one of my users. 

I'm following the instructions in the README.md.  I'm able to download the data (though I also ran into the issue in #12 and had to obtain the data manually).  I'm also able to index the data.  But when I try to build and initialize the database I encounter the following:
```
$ java -jar asdpex-cli/target/asdpex-cli-0.2.jar create-db -s asdpex.sqlite -d data
[INFO] Create database
[INFO] Opened database successfully
Table created successfully
Table created successfully
Table created successfully
[INFO] Updated alt scaffold accessions
[INFO] Updated chromosome accessions
[INFO] Updated regions
java.io.FileNotFoundException: data/genomic_regions_definitions.txt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at de.charite.compbio.asdpex.util.IOUtil.getBufferedReaderFromFileName(IOUtil.java:76)
        at de.charite.compbio.asdpex.io.parser.RegionInfoParser.parse(RegionInfoParser.java:58)
        at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.createAlternativeScaffoldTables(CreateDatabaseCommand.java:112)
        at de.charite.compbio.asdpex.cmd.CreateDatabaseCommand.run(CreateDatabaseCommand.java:72)
        at de.charite.compbio.asdpex.App.main(App.java:58)
[INFO] Updated alt scaffold placement
``` 
Here is what my data directory looks like:
```
$ tree data
data
├── TMP
│   └── alt_scaffold_placement.txt
├── all_alt_scaffold_placement.txt
├── alts_accessions_GRCh38.p2
├── chr_accessions_GRCh38.p2
└── genome
    ├── GRCh38.fa
    ├── GRCh38.fa.fai
    └── GRCh38.fa.gz

2 directories, 7 files
```
Am I supposed to have `genomic_regions_definitions.txt` somewhere?  How am I supposed to obtain or generate this file?  Thank you.

**Comment by martenj** [comment]
Hi,
thanks for reaching out. I also noticed that the download script is not up to date anymore. I will take care of that soon.
The download script in the script folder is still pointing to the regions file under ```ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.107/chr_context_for_alt_loci/GRCh38.p2/genomic_regions_definitions.txt``` 

You can download this file via
```
git clone https://github.com/charite/asdpex.git
cd asdpex/scripts
./downloadData.sh region
```

Best.

**Comment by GodloveD** [comment]
Thanks very much for your quick response @martenj!  Your suggestion allowed me to build the database.  But now I'm stuck at the next step of the README.md.  
```
$ java -jar asdpex-cli/target/asdpex-cli-0.2.jar align -d data/ -s seqan/regionalign2vcf -o alignresults -q asdpex.sqlite
[INFO] Reference fastA file checked: data//genome/GRCh38.fa
[INFO] SeqAn aligner checked: seqan/regionalign2vcf
[INFO] Opened database successfully
[INFO] loaded 213 alternate loci placements
        [INFO] processing alt. loci
        0%       50%       100%
        |.........|.........|
        *[WARN] skipping - missing GFF file
java.io.FileNotFoundException: Missing file: data/alignments/NT_187515.1_NC_000001.11.gff
        at de.charite.compbio.asdpex.cmd.AlignCommand.getAlignments(AlignCommand.java:213)
        at de.charite.compbio.asdpex.cmd.AlignCommand.run(AlignCommand.java:126)
        at de.charite.compbio.asdpex.App.main(App.java:58)
[WARN] skipping - missing GFF file
java.io.FileNotFoundException: Missing file: data/alignments/NT_187517.1_NC_000001.11.gff
        at de.charite.compbio.asdpex.cmd.AlignCommand.getAlignments(AlignCommand.java:213)
        at de.charite.compbio.asdpex.cmd.AlignCommand.run(AlignCommand.java:126)
        at de.charite.compbio.asdpex.App.main(App.java:58)
[WARN] skipping - missing GFF file
java.io.FileNotFoundException: Missing file: data/alignments/NT_187514.1_NC_000001.11.gff
        at de.charite.compbio.asdpex.cmd.AlignCommand.getAlignments(AlignCommand.java:213)
        at de.charite.compbio.asdpex.cmd.AlignCommand.run(AlignCommand.java:126)
        at de.charite.compbio.asdpex.App.main(App.java:58)
[snip...]
```
This is followed by >200 similar warnings, and the `alignresults` directory is not created.  Looks like I'm also missing a lot of other files.  Is this also an issue with the download script?

**Comment by martenj** [comment]
Hi,

looks like you are also missing the GFF alignment files provided by NCBI. It should work like for the regions file.
The download parameter for these is `aln`:
```
git clone https://github.com/charite/asdpex.git
cd asdpex/scripts
./downloadData.sh aln
```
I hope that works for you.

Best.

**Comment by GodloveD** [comment]
Hi again @martenj.  The end user that I've been working with has been able to manually download all of the appropriate files and successfully run asdpex on their own data.  It sounds like it took lots of time to acquire the appropriate files and to correct all of the paths so that asdpex can find the data that is needed.  It looks several issues have been raised that could be fixed by updating the data download script.  It also looks like you've made some updates earlier this month to try to improve the download script.  So thanks for your help!
